### ISSUE TITLE
End of the line for this old BOM Core Component replacement

### ISSUE THREAD

**Issue by tomlut** [DavidFW1960/bom_core_replacement#2]
Errors received:

```
Logger: custom_components.bom.sensor
Source: custom_components/bom/sensor.py:287 
Integration: bom 
First occurred: 0:07:23 (5 occurrences) 
Last logged: 0:07:23

Check BOM ('Expecting value: line 1 column 1 (char 0)',)
```

```
Logger: custom_components.bom.sensor
Source: custom_components/bom/sensor.py:142 
Integration: bom (documentation) 
First occurred: 0:07:23 (5 occurrences) 
Last logged: 0:07:23

Received error from BOM Current: Expecting value: line 1 column 1 (char 0)
```

I realise that this is not a maintained integration and was only a stop-gap and am not sure if you have any interest in fixing it (or even if you can).

**Comment by lits101** [comment]
I've been having the same issue for a few days. 

> `Logger: custom_components.bom.weather
> Source: custom_components/bom/weather.py:32
> Integration: bom (documentation)
> First occurred: 8:13:06 AM (1 occurrences)
> Last logged: 8:13:06 AM
> 
> Received error from BOM_Current: Expecting value: line 1 column 1 (char 0)`

> `Logger: custom_components.bom.sensor
> Source: custom_components/bom/sensor.py:287
> Integration: bom (documentation)
> First occurred: 8:13:06 AM (1 occurrences)
> Last logged: 8:13:06 AM
> 
> Check BOM ('Expecting value: line 1 column 1 (char 0)',)`

**Comment by DavidFW1960** [comment]
> I realise that this is not a maintained integration and was only a stop-gap and am not sure if you have any interest in fixing it (or even if you can).

@exxamalte may be able to help but honestly guys it's time....

Well this is the answer isn't it... I certainly can't fix it and as you say it was just to give people time to migrate to the new custom component. Looks like none of you can put that off any longer....

BOM Custom Component: https://github.com/bremor/bureau_of_meteorology
BOM Custom Radar Card: https://github.com/theOzzieRat/bom-radar-card
